### ISSUE TITLE
метод для получения конфигурации ключевых слов для фригана

### ISSUE THREAD

**Issue by lejafo** [catebi/Catebi.Api#78]
после того, как будет готова задачка #76 с проектированием табличек для хранения конфигурации в схеме `frgn` можно будет браться за эту

сделать метод GetSearchConfig для получения списка поисковых групп-категорий, ориентируясь на этот yaml:

```yaml
groups:
  - name: 'main group'
    keywords:
      - 'ампула'
      - 'бентонит'
      - 'бетонит'
      - 'верёвка'
      - 'вольер'    
      - 'шлейка'
      - 'шприц'
      ...
    include_keywords:
      - 'животное'
      - 'кошачий'
      - 'кошка'
      - 'кот'
  - name: 'additional group 1'
    keywords:
      - 'витамин'
      - 'вкусняшка'
      - 'домик'
      - 'еда'
      - 'звенелка'
      - 'игрушка'
      - 'каталка'
      - 'клетка'
      - 'лакомство'
      - 'лекарство'
      - 'мята'
      - 'наполнитель'
    include_keywords:
      - 'животное'
      - 'кошачий'
      - 'кошка'
      - 'кот'
  - name: 'additional group 2'
    keywords:
      - 'подушка'
    include_keywords:
      - 'бесплатно'
      - 'донат'
      - 'плоская'
      - 'лежанка'
      - 'кошачий'
      - 'кошка'
      - 'кот'
  - name: 'additional group 3'
    keywords:
      - 'переноска'
      - 'миска'
    include_keywords:
      - 'животное'
      - 'кошачий'
      - 'кошка'
      - 'кот'
      - 'собака'
      - 'собачья'
  - name: 'air conditioner group' 
    keywords:
      - 'кондиционер'
      - 'кондей'
      - 'сплитсистема'
      - 'сплит-система'
    exclude_keywords:
      - 'аренда'
      - 'сдается'
      - 'трансфер'
      - 'шампунь'

```
